# Generated by Django 5.0.1 on 2024-01-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='photo',
        ),
        migrations.AlterField(
            model_name='post',
            name='percentage_throughout',
            field=models.CharField(max_length=50),
        ),
    ]
