# Generated by Django 5.0.1 on 2024-01-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_post_photo_alter_post_percentage_throughout'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(default='default_photo.jpg', upload_to=None),
        ),
    ]
